$(function(){
	$(".MenuA1").hover(function(){
		$(this).find(".MenuTitleCommon").css({
			"background-color":"#333",
			"color":"#fff"
		});
		$(this).find(".MenuTitleCommon").next().show();

	},function(){
		$(this).find(".MenuTitleCommon").css({
			"background-color":"",
			"color":""
		});
		$(this).find(".MenuTitleCommon").next().hide();
	});
	$(".ColmumnCommonLi").hover(function(){
		$(this).css("background-color","#dddddd")
	},function(){
		$(this).css("background-color","")
	});
});